### ISSUE TITLE
Mind creating a COPR?

### ISSUE THREAD

**Issue by secretmango** [rusty-snake/fedora-extras#1]
Hey!

really cool repo, I dont know much about rpm spec files currently, and would not want to maintain a COPR that doesnt work.

https://copr.fedorainfracloud.org/coprs/kalvinist/bubblejail/

This person refers to your Repo and discourages using their COPR. 

What would stand against creating a COPR for supported Fedoras and maybe other versions? Creating the spec files should be the most difficult part, which is done.

[I just attempted to create one](https://copr.fedorainfracloud.org/coprs/boredsquirrel/rustysnake-fedoraextras/builds/)

**Comment by rusty-snake** [comment]
### bubblejail.spec

Has to be build without debuginfo. rpmbuild.sh does this by setting `--nodebuginfo` on the rpmbuild command line. For COPR you likely need to set this in the spec file.

### hardened_malloc.spec

Can not be used reliable on COPR due to `-march=native` usage. If you look for a hardened_malloc.spec with proper support for `-march=x86-64-v?` and correct `BuildRequires`, have a look at the one maintained by Tad: https://github.com/divestedcg/rpm-hardened_malloc/blob/master/hardened_malloc.spec.

**Comment by RoyalOughtness** [comment]
@rusty-snake I already copr'd hardened_malloc from this repo. It works: https://copr.fedorainfracloud.org/coprs/qoijjj/hardened_malloc/package/hardened_malloc/

I also copr'd bubblejail from this repo:
https://copr.fedorainfracloud.org/coprs/qoijjj/bubblejail/build/6694557/

**Comment by rusty-snake** [comment]
I'm currently not interested in maintaining a COPR. Mainly due to lack of time.

**Comment by westurner** [comment]
There's also OBS:
- https://en.opensuse.org/Portal:Build_Service
  - https://en.opensuse.org/openSUSE:Build_Service_Tutorial
- https://en.opensuse.org/Portal:Packaging
  - https://en.opensuse.org/openSUSE:Shared_library_packaging_policy

**Comment by westurner** [comment]
- https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets#Supported_processor_platforms
  - x86-64, aarch64, [...] but can't you pass compiler flags to cross compile with whichever optimizations for whichever platform
